steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/finance-tracker:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/finance-tracker:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/finance-tracker:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/finance-tracker:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'finance-tracker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/finance-tracker:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '3600'
      - '--set-env-vars'
      - 'FLASK_ENV=production,DATABASE_URL=sqlite:////tmp/finance.db,GEMINI_API_KEY=AIzaSyDUKA2cFuBE7QDIK8uH36pSHv47IfmQze0'
      - '--port'
      - '5000'

images:
  - 'gcr.io/$PROJECT_ID/finance-tracker:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/finance-tracker:latest'

options:
  logging: CLOUD_LOGGING_ONLY
