version: '3.8'

services:
  db:
    image: postgres:13
    container_name: finance-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: finance-web
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/finance_db
      - SECRET_KEY=a-very-secret-key-for-development
      - FLASK_APP=run.py
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "flask db upgrade && gunicorn --workers 4 --bind 0.0.0.0:5001 wsgi:app"
    volumes:
      - .:/app

volumes:
  postgres_data: