"""Add Asset and DashboardPreferences models

Revision ID: 71abebd2aa6e
Revises: 89d6eecf46ac
Create Date: 2025-10-26 07:07:20.029325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71abebd2aa6e'
down_revision = '89d6eecf46ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('show_accounts', sa.Boolean(), nullable=True),
    sa.Column('show_transactions', sa.Boolean(), nullable=True),
    sa.Column('show_investments', sa.Boolean(), nullable=True),
    sa.Column('show_assets', sa.Boolean(), nullable=True),
    sa.Column('show_receipts', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_preferences')
    op.drop_table('assets')
    # ### end Alembic commands ###
