"""Add gemini_api_key column to users table.

Revision ID: add_gemini_api_key
Revises: add_feedback
Create Date: 2025-11-02 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_gemini_api_key'
down_revision = 'add_feedback'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gemini_api_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gemini_api_key')
    # ### end Alembic commands ###
