"""Add participating_branches field to deals table

Revision ID: b38f28efdd6e
Revises: merge_branches
Create Date: 2025-11-11 08:16:42.563142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38f28efdd6e'
down_revision = 'merge_branches'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participating_branches', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('participating_branches')

    # ### end Alembic commands ###
