"""Convert float to decimal handling

Revision ID: ee00a836339c
Revises: enhance_regex_patterns
Create Date: 2025-11-05 19:17:49.907823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee00a836339c'
down_revision = 'enhance_regex_patterns'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('starting_balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('current_balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('purchase_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.alter_column('current_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('categorization_rules', schema=None) as batch_op:
        batch_op.alter_column('confidence_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('financial_insights', schema=None) as batch_op:
        batch_op.alter_column('amount_impact',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
        batch_op.alter_column('current_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
        batch_op.alter_column('current_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.alter_column('extracted_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('regex_patterns', schema=None) as batch_op:
        batch_op.alter_column('confidence_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)
        batch_op.alter_column('effectiveness_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.5'"))
        batch_op.alter_column('success_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('fail_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'true'"))
        batch_op.alter_column('is_example',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('tax_tags', schema=None) as batch_op:
        batch_op.alter_column('deduction_percentage',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('tax_tags', schema=None) as batch_op:
        batch_op.alter_column('deduction_percentage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('regex_patterns', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_example',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'true'"))
        batch_op.alter_column('fail_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('success_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('effectiveness_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0.5'"))
        batch_op.alter_column('confidence_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.alter_column('extracted_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.alter_column('current_value',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('current_price',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('financial_insights', schema=None) as batch_op:
        batch_op.alter_column('amount_impact',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('categorization_rules', schema=None) as batch_op:
        batch_op.alter_column('confidence_score',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('current_value',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('current_balance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('starting_balance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
