"""Enhance regex_patterns table with tracking and example fields.

Revision ID: enhance_regex_patterns
Revises: add_gemini_api_key
Create Date: 2025-11-02 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'enhance_regex_patterns'
down_revision = 'add_gemini_api_key'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regex_patterns', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('regex_patterns', sa.Column('pattern_type', sa.String(length=50), nullable=True))
    op.add_column('regex_patterns', sa.Column('test_string', sa.Text(), nullable=True))
    op.add_column('regex_patterns', sa.Column('expected_result', sa.Text(), nullable=True))
    op.add_column('regex_patterns', sa.Column('effectiveness_score', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('regex_patterns', sa.Column('success_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('regex_patterns', sa.Column('fail_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('regex_patterns', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('regex_patterns', sa.Column('is_example', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('regex_patterns', sa.Column('last_used', sa.DateTime(), nullable=True))
    op.add_column('regex_patterns', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regex_patterns', 'updated_at')
    op.drop_column('regex_patterns', 'last_used')
    op.drop_column('regex_patterns', 'is_example')
    op.drop_column('regex_patterns', 'is_active')
    op.drop_column('regex_patterns', 'fail_count')
    op.drop_column('regex_patterns', 'success_count')
    op.drop_column('regex_patterns', 'effectiveness_score')
    op.drop_column('regex_patterns', 'expected_result')
    op.drop_column('regex_patterns', 'test_string')
    op.drop_column('regex_patterns', 'pattern_type')
    op.drop_column('regex_patterns', 'description')
    # ### end Alembic commands ###
