#!/usr/bin/env python3
"""
Seed deals data - Real BDO credit card promotional campaigns
Used as fallback when live API is unavailable
"""

SEED_DEALS = [
    # Dine & Entertainment
    {
        "title": "5% Rebate on Shopping and Dining",
        "description": "Get 5% rebate when you dine at partner restaurants",
        "merchant": "Partner Restaurants",
        "category": "Dine",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "percentage",
        "discount_percent": 5.0,
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "25% Off at Premium Dining Partners",
        "description": "Enjoy up to 25% discount at selected high-end restaurants",
        "merchant": "Selected Restaurants",
        "category": "Dine",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "percentage",
        "discount_percent": 25.0,
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Buy 1 Take 1 Beverages",
        "description": "BOGO on selected beverage items when you dine",
        "merchant": "Participating Restaurants",
        "category": "Dine",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "BOGO",
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },

    # Shopping & Online
    {
        "title": "Up to P1,000 Cashback on Shopee 7.7",
        "description": "Get instant cashback on your Shopee purchases during 7.7 sale",
        "merchant": "Shopee",
        "category": "Online",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "cashback",
        "discount_amount": 1000.0,
        "promotion_start_date": "2025-07-01",
        "promotion_end_date": "2025-07-07",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "5% Rebate on Online Purchases",
        "description": "5% rebate on all online shopping transactions",
        "merchant": "Online Merchants",
        "category": "Online",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "percentage",
        "discount_percent": 5.0,
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Shop and Dine Cashback",
        "description": "P500 cashback on shopping + dine transactions",
        "merchant": "Selected Partners",
        "category": "Online",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "cashback",
        "discount_amount": 500.0,
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Extra 10% Off on Lazada Flash Sales",
        "description": "Additional 10% discount on Lazada's hourly flash deals",
        "merchant": "Lazada",
        "category": "Online",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "percentage",
        "discount_percent": 10.0,
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Free Shipping on Zalora Orders",
        "description": "Complimentary shipping on all Zalora purchases",
        "merchant": "Zalora",
        "category": "Online",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "percentage",
        "discount_percent": 0.0,
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },

    # Travel & Transportation
    {
        "title": "JCB Best of Japan Raffle",
        "description": "Chance to win an all-expense paid trip to Japan",
        "merchant": "JCB / Travel Partners",
        "category": "Travel",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "promotional",
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Double Miles on Online Spend",
        "description": "Earn 2x air miles when you spend online",
        "merchant": "Airline Partners",
        "category": "Travel",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "miles",
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Spend Anywhere Cashback",
        "description": "Earn cashback points on every transaction worldwide",
        "merchant": "Anywhere",
        "category": "Travel",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "points",
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Waived Hotel Resort Fees",
        "description": "Get resort fees waived at selected luxury hotels",
        "merchant": "Hotel Chains",
        "category": "Travel",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "percentage",
        "discount_percent": 0.0,
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Free Travel Insurance",
        "description": "Complimentary travel insurance for cardholders",
        "merchant": "Insurance Partners",
        "category": "Travel",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "promotional",
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },

    # Buy Now Pay Later
    {
        "title": "5% Rebate on Shopping",
        "description": "Get 5% rebate on shopping transactions with installment",
        "merchant": "Retail Partners",
        "category": "Buy Now Pay Later",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "percentage",
        "discount_percent": 5.0,
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "5% Rebate on Everyday Spend",
        "description": "5% rebate on all everyday purchases and installments",
        "merchant": "Everywhere",
        "category": "Buy Now Pay Later",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "percentage",
        "discount_percent": 5.0,
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Zero Interest Installment Plans",
        "description": "0% interest on 6-12 month installment plans",
        "merchant": "Participating Merchants",
        "category": "Buy Now Pay Later",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "promotional",
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },

    # Card Exclusives
    {
        "title": "Up to P3,000 Cashback on Spend Anywhere",
        "description": "Earn up to P3,000 cashback when you spend anywhere",
        "merchant": "Everywhere",
        "category": "Card Exclusives",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "cashback",
        "discount_amount": 3000.0,
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Priority Lounge Access",
        "description": "Unlimited access to airport lounges worldwide",
        "merchant": "Airlines & Airports",
        "category": "Card Exclusives",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "promotional",
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Exclusive Dining Events",
        "description": "Invitation to exclusive dining events for cardholders",
        "merchant": "Fine Dining Restaurants",
        "category": "Card Exclusives",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "promotional",
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
    {
        "title": "Concierge Services",
        "description": "24/7 concierge service for travel, dining, and lifestyle",
        "merchant": "Concierge",
        "category": "Card Exclusives",
        "card_issuer": "BDO",
        "card_type": "Credit Card",
        "discount_type": "promotional",
        "promotion_start_date": "2025-01-01",
        "promotion_end_date": "2025-12-31",
        "url": "https://www.deals.bdo.com.ph",
    },
]
